---
include:
  # - board: nice_nano_v2
  #   shield: settings_reset
  - board: nice_nano_v2
    shield: kyria_rev3_left
    snippet: studio-rpc-usb-uart
    cmake_args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: kyria_rev3_right
